FROM randomdude/gcc-cross-x86_64-elf

ENV C_INCLUDE_PATH=/usr/include/

RUN apt-get update && apt-get upgrade -y && apt-get install -y nasm gcc-multilib g++-multilib xorriso grub-pc-bin grub-common build-essential libc6-dev

VOLUME /root/env
WORKDIR /root/env